version: '3'

services:
  matcher-api:
    build:
      context: matcher-api
    volumes:
      - ./matcher-api:/app/
    ports:
      - "5001:5000"
  ui:
    build:
      context: ui
    volumes:
      - ./ui/:/app/
      # prevent host system's node_modules to be mounted
      - exclude:/app/node_modules/
    ports:
      - "3000:3000"
volumes:
  exclude: